package helpers

import (
	"os"
)

func Env() string {
	val := os.Getenv("WAVE_ENV")
	if val == "" {
		return "production"
	}
	return val
}

func Production() bool {
	return Env() == "production"
}

func Development() bool {
	return Env() == "development"
}

// Determine if the command was generated by `go test`
func Testing() bool {
	if len(os.Args) < 1 {
		return false
	}

	cmd := os.Args[0]

	if len(cmd) < 4 {
		return false
	}

	return cmd[len(cmd)-4:] == "test"
}
